_target_: src.datasets.huggingface_dataset.UpStageDialoguesDataset
data_path: ${connected_dir}/data
split: ${split.train}
target_column_name: ${target_column_name}
num_devices: ${devices}
batch_size: ${batch_size}
pretrained_model_name: ${pretrained_model_name}
data_max_length: ${data_max_length}
target_max_length: ${target_max_length}
